apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-rabbitmq-publish
spec:
  template:
    spec:
      containers:
      - name: rabbitmq-client
        image: {{ .Values.image.repository }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["send",  "amqp://user:{{ .Values.rabbitmq.password }}@rabbitmq.default.svc.cluster.local:5672", "300"]
      restartPolicy: Never
  backoffLimit: 4
