{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "1-helm3.serviceAccountName" . }}
  labels:
{{ include "1-helm3.labels" . | nindent 4 }}
{{- end -}}
